version: "2"

services:
  # REDIS
  redis:
    image: redis:alpine
    container_name: redis_dso
    ports:
      - 6379:6379
  # PHP
  php:
    build:
      context: ./docker/container/php
      args:
        TIMEZONE: ${TIMEZONE}
    container_name: php_dso
    links:
      - redis
    volumes:
     - ${SYMFONY_APP_PATH}:/var/www/dso:rw
  # NGINX
  nginx:
    build:
      context: ./docker/container/nginx
    container_name: nginx_dso
    ports:
     - 80:80
    volumes_from:
      - php