<?php
/**
 * Created by PhpStorm.
 * User: stephane
 * Date: 20/04/18
 * Time: 20:44
 */

namespace Tests\AppBundle\Astrobin;


use Symfony\Bundle\FrameworkBundle\Test\WebTestCase;

class AstrobinTest extends \PHPUnit_Framework_TestCase
{

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
    }


    public function testGetObject()
    {
//        $webServiceTest = new self::astro
    }

    public function testTodayImage()
    {

    }

}