services:
  # Events
  app.eventsubscriber.localesubscriber:
    class: AppBundle\EventSubscriber\LocaleSubscriber
    arguments: ['%kernel.default_locale%']
    tags: [kernel.event_subscriber]

  # Services
  app.helper.kuzzle:
    class: AppBundle\Kuzzle\KuzzleHelper
    arguments:
      - "%kuzzle_host%"
      - "%kuzzle_index%"
      - "%kuzzle_port%"

  # WebServices
  astrobin.webservice:
    class: AppBundle\Astrobin\AstrobinWebService
    abstract: true
    arguments:
     - "%astrobin.key%"
     - "%astrobin.secret%"
  astrobin.webservice.getobject:
    class: AppBundle\Astrobin\Services\getObject
    parent: astrobin.webservice
  astrobin.webservice.gettodayimage:
    class: AppBundle\Astrobin\Services\getTodayImage
    parent: astrobin.webservice

  # Repositories
  app.repository.messier:
    class: AppBundle\Repository\MessierRepository
    arguments:
      - "@app.helper.kuzzle"