services:
  # Events
  app.eventsubscriber.localesubscriber:
    class: AppBundle\EventSubscriber\LocaleSubscriber
    arguments: ['%kernel.default_locale%']
    tags: [kernel.event_subscriber]

  app.eventlistener.exceptionlistener:
    class: AppBundle\EventListener\ExceptionListener
    arguments: ["@templating","@kernel"]
    tags:
      - { name: kernel.event_listener, event: kernel.exception }

  # Services
  app.helper.kuzzle:
    class: AppBundle\Kuzzle\KuzzleHelper
    arguments:
      - "%kuzzle_host%"
      - "%kuzzle_index%"
      - "%kuzzle_port%"

  # WebServices
  astrobin.webservice:
    class: Astrobin\AbstractWebService
    abstract: true
    arguments:
     - "%astrobin.key%"
     - "%astrobin.secret%"
  astrobin.webservice.getimage:
    class: Astrobin\Services\GetImage
    parent: astrobin.webservice
  astrobin.webservice.getcollection:
    class: Astrobin\Services\GetCollection
    parent: astrobin.webservice
  astrobin.webservice.getlocation:
    class: Astrobin\Services\GetLocation
    parent: astrobin.webservice
  astrobin.webservice.gettodayimage:
    class: Astrobin\Services\GetTodayImage
    parent: astrobin.webservice

  # Repositories
  app.repository.abstractobject:
    class: AppBundle\Repository\AbstractKuzzleRepository
    abstract: true
    arguments:
      - "@app.helper.kuzzle"
  app.repository.messier:
    class: AppBundle\Repository\MessierRepository
    parent: app.repository.abstractobject
    arguments:
      - "@astrobin.webservice.getimage"
      - '@app.helper.urlgenerator'

  # Form
  app.form.list_order:
    class: AppBundle\Form\ListOrderFormType
    arguments: ['%list.messier.order%']
    tags:
        - { name: form.type, alias: 'list_order' }
  # Helper
  app.helper.urlgenerator:
    class: AppBundle\Helper\GenerateUrlHelper
    arguments: ['@router']

  # Twig
#  app.twig.dso_twig_extension:
#    class: AppBundle\Twig\DsoTwigExtension
#    tags:
#      - { name: twig.extension }